### ISSUE TITLE
Weird error 127

### ISSUE THREAD

**Issue by Yzord** [whphhg/vanillacoind-web-ui#1]
Hi,

I want to try this one out (on a clean Ubuntu) but i receive this error:

>~/vanillacoind-web-ui# npm start

> vanillacoind-web-ui@0.1.0 start /root/vanillacoind-web-ui
> node ./bin/www

>sh: 1: node: not found
>npm ERR! weird error 127
>npm WARN This failure might be due to the use of legacy binary "node"
>npm WARN For further explanations, please read
>/usr/share/doc/nodejs/README.Debian

>npm ERR! not ok code 0[/quote]

I think it is a stupid question, but do i need a vanilla node for this?

**Comment by whphhg** [comment]
Hey,

Thanks for trying it out. As you've already guessed, you need a running wallet. :)
